name: Export Hugo (NO PROD)

on:
  push:
    branches: ["!main"]
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
      contents: read
      pages: write
      id-token: write

jobs:
  test-hugo-devoxxpl:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: '0.147.2'
      HUGO_ENVIRONMENT: 'production'
      TZ: 'Europe/Paris'
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Install Dart Sass
        run: sudo snap install dart-sass
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
      - name: Configure Git
        run: git config core.quotepath false
      - name: Build with Hugo
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/devoxxpl/" \
            -s ./docs \
            -d ../public/devoxxpl